// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Footer → Footer Links*
 */
export interface FooterDocumentDataFooterLinksItem {
  /**
   * Link field in *Footer → Footer Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Footer → Support Emails*
 */
export interface FooterDocumentDataSupportEmailsItem {
  /**
   * Email Address field in *Footer → Support Emails*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.support_emails[].email_address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_address: prismic.KeyTextField;
}

/**
 * Item in *Footer → Social Links*
 */
export interface FooterDocumentDataSocialLinksItem {
  /**
   * Link field in *Footer → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Social Icon field in *Footer → Social Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[].social_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_icon: prismic.ImageField<never>;
}

/**
 * Item in *Footer → Office addresses*
 */
export interface FooterDocumentDataOfficeAddressesItem {
  /**
   * Flag field in *Footer → Office addresses*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.office_addresses[].flag
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  flag: prismic.ImageField<never>;

  /**
   * Address field in *Footer → Office addresses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.office_addresses[].address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Footer Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_links: prismic.GroupField<Simplify<FooterDocumentDataFooterLinksItem>>;

  /**
   * Support Emails field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.support_emails[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  support_emails: prismic.GroupField<
    Simplify<FooterDocumentDataSupportEmailsItem>
  >;

  /**
   * Social Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_links: prismic.GroupField<Simplify<FooterDocumentDataSocialLinksItem>>;

  /**
   * Office addresses field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.office_addresses[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  office_addresses: prismic.GroupField<
    Simplify<FooterDocumentDataOfficeAddressesItem>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type LandingPagesDocumentDataSlicesSlice =
  | FeatureOptionsSlice
  | FeatureItemSlice
  | VesicashFeaturesSlice
  | VesicashOptionsSlice
  | PartnersSlice
  | OnboardSlice
  | DocumentationSlice
  | HeroSectionSlice;

/**
 * Content for Landing Pages documents
 */
interface LandingPagesDocumentData {
  /**
   * Slice Zone field in *Landing Pages*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_pages.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingPagesDocumentDataSlicesSlice> /**
   * Meta Title field in *Landing Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing_pages.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Landing Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing_pages.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing Pages*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_pages.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Keywords field in *Landing Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_pages.meta_keywords
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField;
}

/**
 * Landing Pages document from Prismic
 *
 * - **API ID**: `landing_pages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPagesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPagesDocumentData>,
    "landing_pages",
    Lang
  >;

export type AllDocumentTypes = FooterDocument | LandingPagesDocument;

/**
 * Primary content in *Documentation → Default → Primary*
 */
export interface DocumentationSliceDefaultPrimary {
  /**
   * Title field in *Documentation → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: documentation.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Documentation → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: documentation.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Documentation Link field in *Documentation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: documentation.default.primary.documentation_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  documentation_link: prismic.LinkField;

  /**
   * Documentation Illustration field in *Documentation → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: documentation.default.primary.documentation_illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  documentation_illustration: prismic.ImageField<never>;
}

/**
 * Default variation for Documentation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DocumentationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DocumentationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Documentation*
 */
type DocumentationSliceVariation = DocumentationSliceDefault;

/**
 * Documentation Shared Slice
 *
 * - **API ID**: `documentation`
 * - **Description**: Documentation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DocumentationSlice = prismic.SharedSlice<
  "documentation",
  DocumentationSliceVariation
>;

/**
 * Primary content in *FeatureItem → Default → Primary*
 */
export interface FeatureItemSliceDefaultPrimary {
  /**
   * Title field in *FeatureItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_item.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *FeatureItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_item.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * illustration field in *FeatureItem → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_item.default.primary.illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>;

  /**
   * Illustration Position field in *FeatureItem → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Whether to place the illustration by left or right
   * - **Default Value**: right
   * - **API ID Path**: feature_item.default.primary.illustration_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  illustration_position: prismic.SelectField<"right" | "left", "filled">;

  /**
   * Theme field in *FeatureItem → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: grey
   * - **API ID Path**: feature_item.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"grey" | "green" | "transparent", "filled">;
}

/**
 * Default variation for FeatureItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureItem*
 */
type FeatureItemSliceVariation = FeatureItemSliceDefault;

/**
 * FeatureItem Shared Slice
 *
 * - **API ID**: `feature_item`
 * - **Description**: FeatureItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureItemSlice = prismic.SharedSlice<
  "feature_item",
  FeatureItemSliceVariation
>;

/**
 * Item in *FeatureOptions → Default → Primary → Options*
 */
export interface FeatureOptionsSliceDefaultPrimaryOptionsItem {
  /**
   * Title field in *FeatureOptions → Default → Primary → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_options.default.primary.options[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *FeatureOptions → Default → Primary → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_options.default.primary.options[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Icon field in *FeatureOptions → Default → Primary → Options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_options.default.primary.options[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Primary content in *FeatureOptions → Default → Primary*
 */
export interface FeatureOptionsSliceDefaultPrimary {
  /**
   * Title field in *FeatureOptions → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_options.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *FeatureOptions → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_options.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Options field in *FeatureOptions → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_options.default.primary.options[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  options: prismic.GroupField<
    Simplify<FeatureOptionsSliceDefaultPrimaryOptionsItem>
  >;

  /**
   * Theme field in *FeatureOptions → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: grey
   * - **API ID Path**: feature_options.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"grey" | "green" | "transparent", "filled">;
}

/**
 * Default variation for FeatureOptions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureOptionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureOptionsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureOptions*
 */
type FeatureOptionsSliceVariation = FeatureOptionsSliceDefault;

/**
 * FeatureOptions Shared Slice
 *
 * - **API ID**: `feature_options`
 * - **Description**: FeatureOptions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureOptionsSlice = prismic.SharedSlice<
  "feature_options",
  FeatureOptionsSliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Get Started Link field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.get_started_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  get_started_link: prismic.LinkField;

  /**
   * Hero Illustration field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.hero_illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_illustration: prismic.ImageField<never>;

  /**
   * Position Offset field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Controls to top-to-down position of the illustration
   * - **API ID Path**: hero_section.default.primary.position_offset
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  position_offset: prismic.NumberField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroSection → Tagged → Primary*
 */
export interface HeroSectionSliceTaggedPrimary {
  /**
   * Title field in *HeroSection → Tagged → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.tagged.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *HeroSection → Tagged → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.tagged.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Hero Tag field in *HeroSection → Tagged → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.tagged.primary.hero_tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_tag: prismic.KeyTextField;

  /**
   * Hero Illustration field in *HeroSection → Tagged → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.tagged.primary.hero_illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_illustration: prismic.ImageField<never>;

  /**
   * Position Offset field in *HeroSection → Tagged → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Controls to top-to-down position of the illustration
   * - **API ID Path**: hero_section.tagged.primary.position_offset
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  position_offset: prismic.NumberField;
}

/**
 * Tagged variation for HeroSection Slice
 *
 * - **API ID**: `tagged`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceTagged = prismic.SharedSliceVariation<
  "tagged",
  Simplify<HeroSectionSliceTaggedPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation =
  | HeroSectionSliceDefault
  | HeroSectionSliceTagged;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *Onboard → Default → Primary*
 */
export interface OnboardSliceDefaultPrimary {
  /**
   * Title field in *Onboard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: onboard.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Onboard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: onboard.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Booking Link field in *Onboard → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: onboard.default.primary.booking_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  booking_link: prismic.LinkField;
}

/**
 * Default variation for Onboard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OnboardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OnboardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Onboard*
 */
type OnboardSliceVariation = OnboardSliceDefault;

/**
 * Onboard Shared Slice
 *
 * - **API ID**: `onboard`
 * - **Description**: Onboard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OnboardSlice = prismic.SharedSlice<
  "onboard",
  OnboardSliceVariation
>;

/**
 * Item in *Partners → Default → Primary → Logos*
 */
export interface PartnersSliceDefaultPrimaryLogosItem {
  /**
   * Logo field in *Partners → Default → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.logos[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *Partners → Default → Primary*
 */
export interface PartnersSliceDefaultPrimary {
  /**
   * Title field in *Partners → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Partners → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Logos field in *Partners → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logos: prismic.GroupField<Simplify<PartnersSliceDefaultPrimaryLogosItem>>;
}

/**
 * Default variation for Partners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Partners*
 */
type PartnersSliceVariation = PartnersSliceDefault;

/**
 * Partners Shared Slice
 *
 * - **API ID**: `partners`
 * - **Description**: Partners
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSlice = prismic.SharedSlice<
  "partners",
  PartnersSliceVariation
>;

/**
 * Item in *VesicashFeatures → Default → Primary → Features*
 */
export interface VesicashFeaturesSliceDefaultPrimaryFeaturesItem {
  /**
   * Title field in *VesicashFeatures → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vesicash_features.default.primary.features[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *VesicashFeatures → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vesicash_features.default.primary.features[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Illustration field in *VesicashFeatures → Default → Primary → Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: vesicash_features.default.primary.features[].illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>;

  /**
   * Theme field in *VesicashFeatures → Default → Primary → Features*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Controls the color gradient of each card
   * - **Default Value**: blue
   * - **API ID Path**: vesicash_features.default.primary.features[].theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"blue" | "green" | "bluish", "filled">;
}

/**
 * Primary content in *VesicashFeatures → Default → Primary*
 */
export interface VesicashFeaturesSliceDefaultPrimary {
  /**
   * Illustration field in *VesicashFeatures → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: vesicash_features.default.primary.illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>;

  /**
   * Features field in *VesicashFeatures → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: vesicash_features.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<VesicashFeaturesSliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for VesicashFeatures Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VesicashFeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VesicashFeaturesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VesicashFeatures*
 */
type VesicashFeaturesSliceVariation = VesicashFeaturesSliceDefault;

/**
 * VesicashFeatures Shared Slice
 *
 * - **API ID**: `vesicash_features`
 * - **Description**: VesicashFeatures
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VesicashFeaturesSlice = prismic.SharedSlice<
  "vesicash_features",
  VesicashFeaturesSliceVariation
>;

/**
 * Item in *VesicashOptions → Default → Primary → Options*
 */
export interface VesicashOptionsSliceDefaultPrimaryOptionsItem {
  /**
   * Title field in *VesicashOptions → Default → Primary → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vesicash_options.default.primary.options[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *VesicashOptions → Default → Primary → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vesicash_options.default.primary.options[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Illustration field in *VesicashOptions → Default → Primary → Options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: vesicash_options.default.primary.options[].illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>;
}

/**
 * Primary content in *VesicashOptions → Default → Primary*
 */
export interface VesicashOptionsSliceDefaultPrimary {
  /**
   * Options field in *VesicashOptions → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: vesicash_options.default.primary.options[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  options: prismic.GroupField<
    Simplify<VesicashOptionsSliceDefaultPrimaryOptionsItem>
  >;
}

/**
 * Default variation for VesicashOptions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VesicashOptionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VesicashOptionsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VesicashOptions*
 */
type VesicashOptionsSliceVariation = VesicashOptionsSliceDefault;

/**
 * VesicashOptions Shared Slice
 *
 * - **API ID**: `vesicash_options`
 * - **Description**: VesicashOptions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VesicashOptionsSlice = prismic.SharedSlice<
  "vesicash_options",
  VesicashOptionsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataFooterLinksItem,
      FooterDocumentDataSupportEmailsItem,
      FooterDocumentDataSocialLinksItem,
      FooterDocumentDataOfficeAddressesItem,
      LandingPagesDocument,
      LandingPagesDocumentData,
      LandingPagesDocumentDataSlicesSlice,
      AllDocumentTypes,
      DocumentationSlice,
      DocumentationSliceDefaultPrimary,
      DocumentationSliceVariation,
      DocumentationSliceDefault,
      FeatureItemSlice,
      FeatureItemSliceDefaultPrimary,
      FeatureItemSliceVariation,
      FeatureItemSliceDefault,
      FeatureOptionsSlice,
      FeatureOptionsSliceDefaultPrimaryOptionsItem,
      FeatureOptionsSliceDefaultPrimary,
      FeatureOptionsSliceVariation,
      FeatureOptionsSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceTaggedPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      HeroSectionSliceTagged,
      OnboardSlice,
      OnboardSliceDefaultPrimary,
      OnboardSliceVariation,
      OnboardSliceDefault,
      PartnersSlice,
      PartnersSliceDefaultPrimaryLogosItem,
      PartnersSliceDefaultPrimary,
      PartnersSliceVariation,
      PartnersSliceDefault,
      VesicashFeaturesSlice,
      VesicashFeaturesSliceDefaultPrimaryFeaturesItem,
      VesicashFeaturesSliceDefaultPrimary,
      VesicashFeaturesSliceVariation,
      VesicashFeaturesSliceDefault,
      VesicashOptionsSlice,
      VesicashOptionsSliceDefaultPrimaryOptionsItem,
      VesicashOptionsSliceDefaultPrimary,
      VesicashOptionsSliceVariation,
      VesicashOptionsSliceDefault,
    };
  }
}
